version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gorm.com
      PGADMIN_DEFAULT_PASSWORD: gorm
    ports: 
      - 5050:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin
  vault:
    image: hashicorp/vault
    ports:
      - 8200:8200
    volumes:
      - private-volume:/vault/file:rw
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-only-token
    cap_add:
      - IPC_LOCK
volumes:
  postgres-data:
  pgadmin-data:
  private-volume:
